global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerting'
