version: '3.3'
services:
  post_db:
    image: mongo:${MONGOVER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases: 
          - comment_db
          - post_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - ${UIPORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - front_net
      - back_net
volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
